Bugfix/remove selectors
SquiggleTools/SquiggleConf pull request #91
Opened 2024-07-17 02:54 UTC by abhijit360

## PR Checklist

- [ done] Addresses an existing open issue: fixes #88
- [ done] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/SquiggleConf/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [done ] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/SquiggleConf/blob/main/.github/CONTRIBUTING.md) were taken

## Overview
Added a noselect class from this [`stackoverflow`](https://stackoverflow.com/questions/29908261/prevent-text-selection-on-mouse-drag) answer. I tested it locally and it appears to work

2024-07-23 12:51 UTC, JoshuaKGoldberg commented on package-lock.json
Ah, it looks like you used `npm install` instead of `pnpm install`. You'll want to delete this file.

See https://pnpm.io/ for docs on pnpm.

2024-07-23 16:43 UTC, JoshuaKGoldberg requested changes
A good start, thanks! 🙌

2024-08-19 18:46 UTC, JoshuaKGoldberg commented
👋 @abhijit360 do you still have energy + time to work on this?

2024-08-19 20:04 UTC, abhijit360 commented
Yes! I will have the PR in this week

2024-09-03 22:46 UTC, JoshuaKGoldberg commented
(talked offline: may have time later)

2024-09-03 22:46 UTC, closed without merging